name = "cLHAPDF"
uuid = "633b9f2c-654d-4886-93c1-b219cb2e426c"
authors = ["Youjack <iamjasonlin@163.com>"]
version = "0.1.0"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[compat]
julia = ">= 1.11"
